AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

  Exclude:
    - "bin/**/*"
    - "sample/*"


# Soon...
Gemspec/RequireMFA:
 Enabled: false

# I'm okay with more complex methods in specs.
Metrics/AbcSize:
  Max: 25
  Include:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case

# I like to use the hash rocket in rake files and the sample.
Style/HashSyntax:
  Exclude:
    - "Rakefile"
    - "sample/*"

# I am not going to optimize by freezing strings.
Style/FrozenStringLiteralComment:
  Enabled: false

# I'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I am not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false

# I am not going to distinguish between fail and raise.
Style/SignalException:
  Enabled: false

# I'm not so fond of %i for symbol arrays.
Style/SymbolArray:
  Enabled: false

# I'm not so fond of %w for word arrays.
Style/WordArray:
  Enabled: false
